---
- name: Install Apache2 and copy index.html
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Copy index.html
      copy:
        src: "{{ WORKSPACE }}/RandomYeet/index.html"
        dest: /var/www/html/index.html
